name: Deploy Flask to EC2

on:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4
        with:
          ref: deploy-test  # 정확한 브랜치 체크아웃!

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/GG.V2  # 프로젝트 디렉토리 이동
            git pull origin deploy-test  # 최신 코드 가져오기
            source venv/bin/activate  # 가상환경 활성화
            pip install -r requirements.txt  # 의존성 업데이트
            pkill -f "gunicorn" || true  # 기존 실행 중인 프로세스 종료 (없어도 오류 안 나게)
            nohup gunicorn -w 4 -b 0.0.0.0:8000 run:app &  # Flask 실행 (gunicorn 사용)

